# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # https://github.com/marketplace/actions/flutter-action
      - name: Use Flutter Action
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'master'
      
      - run: flutter pub get
      - run: flutter build apk
